fail_fast: true

repos:
  - repo: local
    hooks:
      - id: whitespace-check
        name: whitespace check
        entry: git diff --cached --check
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check
        language: system
        types_or: [python]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types_or: [python]

      - id: ty-check
        name: ty check
        entry: uv run ty check
        language: system
        types_or: [python]

      - id: clang-format
        name: clang-format
        entry: clang-format --dry-run --Werror
        language: system
        types_or: [c, c++, cuda]

      - id: doxygen
        name: doxygen
        entry: doxygen Doxyfile
        language: system
        files: ^(Doxyfile|src/cext/.*\.(c|cc|cpp|cu|cuh|h|hh|hpp))$
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
