[atn]
devices = [0, 1]

[ffn]
devices = [2]

[scheduler]
ffn_concurrency = 1

[scheduler.slo]
ttft_ms = 1000
tbt_ms = 50

[[models]]
id = "Qwen/Qwen3-14B"
atn_tp_size = 2
atn_dp_size = 1
ffn_tp_size = 1
