include_guard(GLOBAL)

if(XPOOL_ENABLE_CCACHE)
  find_program(XPOOL_CCACHE_PROGRAM ccache)
  if(XPOOL_CCACHE_PROGRAM)
    set(XPOOL_CCACHE_LANGS)
    foreach(XPOOL_CCACHE_LANG IN ITEMS C CXX CUDA)
      if(NOT CMAKE_${XPOOL_CCACHE_LANG}_COMPILER_LAUNCHER)
        set(CMAKE_${XPOOL_CCACHE_LANG}_COMPILER_LAUNCHER "${XPOOL_CCACHE_PROGRAM}")
        list(APPEND XPOOL_CCACHE_LANGS "${XPOOL_CCACHE_LANG}")
      endif()
    endforeach()
    if(XPOOL_CCACHE_LANGS)
      list(JOIN XPOOL_CCACHE_LANGS ", " XPOOL_CCACHE_LANGS_TEXT)
      message(STATUS "Using ccache compiler launcher for ${XPOOL_CCACHE_LANGS_TEXT}: ${XPOOL_CCACHE_PROGRAM}")
    else()
      message(STATUS "ccache found but compiler launchers are already configured; keeping existing launchers")
    endif()
  endif()
endif()
